### ISSUE TITLE
No changes occur but I get an alert

### ISSUE THREAD

**Issue by GoogleCodeExporter** [max99x/pagemon-chrome-ext#291]
```
What steps will reproduce the problem? Please include a URL.
Want to monitor the number of products of an amazon search:
http://www.amazon.com/s/ref=sr_nr_i_0?rh=k%3Aspecific+product+xyz%2Ci%3Astripboo
ks&keywords=specific+product+xyz&ie=UTF8&qid=1401175296
Therefore I selected the area of founded number of results in the header:
#number results for BooksBooks : "specific product xyz"

What is the expected output? What do you see instead?
Expect that in every changed number of results I get a notification. Instead I 
get every time a notification after a check. (I assume that the website link 
may be the trigger.) It would be best if I get an alarm only when the result 
number rises (e.g. 5-->8).

What version of the Chrome are you using? On what operating system?
Page Monitor Version 3.3.3
Chrome Version 35.0.1916.114
OS X Version 10.9.3


What are the error log messages?
126
Refused to execute inline event handler because it violates the following 
Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either 
the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is 
required to enable inline execution.
 background.htm:1
Uncaught TypeError: Cannot read property 'length' of undefined 
scripts/popup.js:2
18
Refused to execute inline event handler because it violates the following 
Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either 
the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is 
required to enable inline execution.
 background.htm:1
Error in response handler for tabs.insertCSS: The tab was closed.
    at Object.callback (chrome-extension://pemhgklkefakciniebenbfclihhmmfcd/scripts/options.js:37:352) background.htm:1
Error in response handler for tabs.executeScript: No tab with id: 493.
    at Object.callback (chrome-extension://pemhgklkefakciniebenbfclihhmmfcd/scripts/options.js:37:294) background.htm:1
28
Refused to execute inline event handler because it violates the following 
Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either 
the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is 
required to enable inline execution.


Please provide any additional information below.
Thanks for your help!
```

Original issue reported on code.google.com by `jacad...@gmail.com` on 27 May 2014 at 7:41

**Comment by GoogleCodeExporter** [comment]
```
I don't see a good Selector solution for this, but this regex might do the 
trick:

[,\d]+ results for 
```

Original comment by `max99x` on 4 Jun 2014 at 6:14
